//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryList
    {
        public CategoryList()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public long CategoryID { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
