//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cork_PostHousing
    {
        public long Id { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> SubCatID { get; set; }
        public string Address { get; set; }
        public string LocationTown { get; set; }
        public string LocationCity { get; set; }
        public Nullable<int> Zip { get; set; }
        public Nullable<int> Zip4 { get; set; }
        public string Country { get; set; }
        public Nullable<int> VilleID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public decimal Price { get; set; }
        public string AdType { get; set; }
        public string Type { get; set; }
        public string Beds { get; set; }
        public string Bath { get; set; }
        public string Laundry { get; set; }
        public string Parking { get; set; }
        public Nullable<int> SquareFt { get; set; }
        public Nullable<bool> Furnished { get; set; }
        public Nullable<bool> CatsOk { get; set; }
        public Nullable<bool> DogsOk { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> Views { get; set; }
    }
}
