//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eusCommonEntities : DbContext
    {
        public eusCommonEntities()
            : base("name=eusCommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admin_ErrorLog> Admin_ErrorLog { get; set; }
        public virtual DbSet<Admin_Log> Admin_Log { get; set; }
        public virtual DbSet<Admin_ToDo> Admin_ToDo { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Geo_Cities> Geo_Cities { get; set; }
        public virtual DbSet<Geo_Countries> Geo_Countries { get; set; }
        public virtual DbSet<Geo_Ville> Geo_Ville { get; set; }
        public virtual DbSet<User_Coins> User_Coins { get; set; }
        public virtual DbSet<User_Flag> User_Flag { get; set; }
        public virtual DbSet<User_Location> User_Location { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<User_Transactions> User_Transactions { get; set; }
        public virtual DbSet<Geo_ZipCodes> Geo_ZipCodes { get; set; }
    
        public virtual ObjectResult<string> GetLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLocations");
        }
    }
}
