//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_ZipCodes
    {
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string AreaCode { get; set; }
        public string CityType { get; set; }
        public string CityAliasAbbreviation { get; set; }
        public string CityAliasName { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> Elevation { get; set; }
        public string CountyFIPS { get; set; }
        public string DayLightSaving { get; set; }
        public string PreferredLastLineKey { get; set; }
        public string ClassificationCode { get; set; }
        public string MultiCounty { get; set; }
        public string StateFIPS { get; set; }
        public string CityStateKey { get; set; }
        public string CityAliasCode { get; set; }
        public string PrimaryRecord { get; set; }
        public string CityMixedCase { get; set; }
        public string CityAliasMixedCase { get; set; }
        public string StateANSI { get; set; }
        public string CountyANSI { get; set; }
        public string FacilityCode { get; set; }
        public string CityDeliveryIndicator { get; set; }
        public string CarrierRouteRateSortation { get; set; }
        public string FinanceNumber { get; set; }
        public string UniqueZIPName { get; set; }
    }
}
