//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Cities
    {
        public int Id { get; set; }
        public int VilleId { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> CityPopulation { get; set; }
        public Nullable<int> CityAsianPopulation { get; set; }
        public Nullable<int> PostalCodePopulation { get; set; }
    }
}
