//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public Nullable<long> TypePostID { get; set; }
        public Nullable<int> ImageMain { get; set; }
        public Nullable<int> ImageCount { get; set; }
        public string Orig1 { get; set; }
        public string Orig2 { get; set; }
        public string Orig3 { get; set; }
        public string Orig4 { get; set; }
        public string Orig5 { get; set; }
        public string Orig6 { get; set; }
        public string Orig7 { get; set; }
        public string Orig8 { get; set; }
        public string Thumb1 { get; set; }
        public string Thumb2 { get; set; }
        public string Thumb3 { get; set; }
        public string Thumb4 { get; set; }
        public string Thumb5 { get; set; }
        public string Thumb6 { get; set; }
        public string Thumb7 { get; set; }
        public string Thumb8 { get; set; }
        public string Display1 { get; set; }
        public string Display2 { get; set; }
        public string Display3 { get; set; }
        public string Display4 { get; set; }
        public string Display5 { get; set; }
        public string Display6 { get; set; }
        public string Display7 { get; set; }
        public string Display8 { get; set; }
    }
}
