//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public long TopicID { get; set; }
        public string Topic1 { get; set; }
        public string TopicURL { get; set; }
        public string Search { get; set; }
        public string Tags { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual CategoryList CategoryList { get; set; }
    }
}
