//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Coins
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<int> Gold { get; set; }
        public Nullable<int> Silver { get; set; }
        public Nullable<int> Bronze { get; set; }
    }
}
