//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Transactions
    {
        public long TransId { get; set; }
        public long UserId { get; set; }
        public int Type { get; set; }
        public Nullable<long> TransGold { get; set; }
        public Nullable<long> TransSilver { get; set; }
        public Nullable<long> TransBronze { get; set; }
        public string Details { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
