//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Location
    {
        public long UserId { get; set; }
        public Nullable<short> Region { get; set; }
        public Nullable<short> VilleOne { get; set; }
        public Nullable<short> VilleTwo { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
    }
}
